export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';

export const FLOORS_LOAD_START = 'FLOORS_LOAD_START';
export const FLOORS_LOAD_SUCCESS = 'FLOORS_LOAD_SUCCESS';
export const FLOORS_LOAD_FAIL = 'FLOORS_LOAD_FAIL';

export const FLOOR_LOAD_START = 'FLOOR_LOAD_START';
export const FLOOR_LOAD_SUCCESS = 'FLOOR_LOAD_SUCCESS';
export const FLOOR_LOAD_FAIL = 'FLOOR_LOAD_FAIL';

export const THREAD_LOAD_START = 'THREAD_LOAD_START';
export const THREAD_LOAD_SUCCESS = 'THREAD_LOAD_SUCCESS';
export const THREAD_LOAD_FAIL = 'THREAD_LOAD_FAIL';

export const THREAD_DELETE = 'THREAD_DELETE';
export const THREAD_DELETE_START = 'THREAD_DELETE_START'
export const THREAD_DELETE_SUCCESS = 'THREAD_DELETE_SUCCESS'
export const THREAD_DELETE_FAIL = 'THREAD_DELETE_SUCCESS'

export const SET_THREAD_CATEGORY = 'SET_THREAD_CATEGORY';

export const THREAD_POST_START = 'THREAD_POST_START';
export const THREAD_POST_SUCCESS = 'THREAD_POST_SUCCESS';
export const THREAD_POST_FAIL = 'THREAD_POST_FAIL';

export const THREAD_EDIT_START = 'THREAD_EDIT_START';
export const THREAD_EDIT_SUCCESS = 'THREAD_EDIT_SUCCESS';
export const THREAD_EDIT_FAIL = 'THREAD_EDIT_FAIL';

export const COMMENT_POST_START = 'COMMENT_POST_START';
export const COMMENT_POST_SUCCESS = 'COMMENT_POST_SUCCESS';
export const COMMENT_POST_FAIL = 'COMMENT_POST_FAIL';

export const COMMENT_DELETE = 'COMMENT_DELETE';
export const COMMENT_DELETE_START = 'COMMENT_DELETE_START'
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS'
export const COMMENT_DELETE_FAIL = 'COMMENT_DELETE_SUCCESS'

export const COMMENT_LOAD_START = 'COMMENT_LOAD_START';
export const COMMENT_LOAD_SUCCESS = 'COMMENT_LOAD_SUCCESS';
export const COMMENT_LOAD_FAIL = 'COMMENT_LOAD_FAIL';


export const GET_CATEGORY = 'GET_CATEGORY';
export const CATEGORY_LOAD_SUCCESS = 'CATEGORY_LOAD_SUCCESS';
export const CATEGORY_LOAD_FAIL = 'CATEGORY_LOAD_FAIL';

